// ============================================================
//  PORTFOLIO DATA — Sarth Narola
// ============================================================

export const PROFILE = {
  name: 'Sarth Narola',
  title: 'Full Stack Developer & AI Engineer',
  tagline: 'Building Scalable AI-Powered Web Applications',
  roles: ['Software Engineer', 'MERN Developer', 'AI Enthusiast', 'Problem Solver'],
  email: 'sarthnarola018@gmail.com',
  nirmaEmail: '23bce194@nirmauni.ac.in',
  rollNo: '23BCE194',
  location: 'Surat, Gujarat, India',
  github: 'https://github.com/Sarth00718',
  linkedin: 'https://linkedin.com/in/sarth-narola-223002323',
  leetcode: 'https://leetcode.com/u/__sarth_narola_007/',
  codeforces: 'https://codeforces.com/profile/sarthnarola007',
  codechef: 'https://www.codechef.com/users/mds_007',
  resumeUrl: '/resume.pdf',
  university: 'Nirma University',
  cgpa: '9.11',
  graduationYear: '2027',
  summary:
    'Final-year Computer Science student specializing in Full Stack Development and AI/ML systems. Experienced in building production-ready applications with MERN stack, RAG pipelines, and modern AI frameworks. Selected for Amazon ML Summer School 2025.',
  expertise: [
    'Full Stack Development (MERN)',
    'AI/ML Integration (RAG, LangChain)',
    'System Design & Architecture',
    'RESTful API Development',
    'Database Design & Optimization',
    'Cloud Deployment (Vercel, Render)',
  ],
  lookingFor: [
    'Software Development Engineer roles',
    'Full Stack Developer positions',
    'AI/ML Engineer opportunities',
    'Product Engineering roles',
  ],
  availability: {
    status: 'Open to Opportunities',
    startDate: 'June 2027',
    type: ['Full-time', 'Internship'],
    location: ['Remote', 'Hybrid', 'On-site'],
  },
};

export const ABOUT_PANELS = [
  {
    id: 'education',
    icon: '🎓',
    label: 'Education',
    title: 'Nirma University',
    subtitle: 'B.Tech Computer Engineering',
    detail: 'CGPA 9.11 · Class of 2027',
    color: '#4F8CFF',
  },
  {
    id: 'location',
    icon: '📍',
    label: 'Location',
    title: 'Surat, Gujarat',
    subtitle: 'India',
    detail: 'Open to Remote / Hybrid / On-site',
    color: '#7DF9FF',
  },
  {
    id: 'interests',
    icon: '🧠',
    label: 'Focus Areas',
    title: 'AI Systems & Full Stack',
    subtitle: 'RAG Pipelines · LLM Apps',
    detail: 'Building production AI products',
    color: '#00F5FF',
  },
  {
    id: 'languages',
    icon: '💬',
    label: 'Languages',
    title: 'English · Hindi · Gujarati',
    subtitle: 'Multilingual',
    detail: 'Fluent communication',
    color: '#A78BFA',
  },
  {
    id: 'softskills',
    icon: '🤝',
    label: 'Soft Skills',
    title: 'Leadership · Collaboration',
    subtitle: 'Problem-Solving · Adaptability',
    detail: 'Hackathon team lead experience',
    color: '#34D399',
  },
  {
    id: 'availability',
    icon: '🚀',
    label: 'Availability',
    title: 'Open to Opportunities',
    subtitle: 'Starting June 2027',
    detail: 'Full-time · Internship',
    color: '#FBBF24',
  },
];

export const SKILL_CATEGORIES = [
  {
    id: 'languages',
    label: 'Languages',
    icon: '⌨️',
    color: '#2563eb',
    bg: 'rgba(37,99,235,0.12)',
    border: 'rgba(37,99,235,0.25)',
    skills: ['JavaScript (ES6+)', 'Python', 'C++', 'Java', 'SQL'],
  },
  {
    id: 'frontend',
    label: 'Frontend',
    icon: '🎨',
    color: '#06b6d4',
    bg: 'rgba(6,182,212,0.1)',
    border: 'rgba(6,182,212,0.25)',
    skills: [
      'React.js',
      'Vite',
      'Tailwind CSS',
      'Framer Motion',
      'Redux Toolkit',
      'HTML5 / CSS3',
      'Bootstrap',
      'Responsive Design',
    ],
  },
  {
    id: 'backend',
    label: 'Backend',
    icon: '⚙️',
    color: '#10b981',
    bg: 'rgba(16,185,129,0.1)',
    border: 'rgba(16,185,129,0.25)',
    skills: ['Node.js', 'Express.js', 'FastAPI', 'REST APIs', 'Socket.IO', 'JWT Auth'],
  },
  {
    id: 'databases',
    label: 'Databases',
    icon: '🗄️',
    color: '#f59e0b',
    bg: 'rgba(245,158,11,0.1)',
    border: 'rgba(245,158,11,0.25)',
    skills: ['MongoDB', 'PostgreSQL', 'MySQL', 'FAISS Vector DB'],
  },
  {
    id: 'ai_ml',
    label: 'AI / ML',
    icon: '🤖',
    color: '#22d3ee',
    bg: 'rgba(14,165,233,0.1)',
    border: 'rgba(14,165,233,0.25)',
    skills: [
      'LangChain',
      'RAG Pipelines',
      'HuggingFace',
      'Groq LLaMA',
      'Google Gemini API',
      'Scikit-learn',
      'Pandas',
      'NumPy',
    ],
  },
  {
    id: 'tools',
    label: 'Tools & DevOps',
    icon: '🛠️',
    color: '#3b82f6',
    bg: 'rgba(59,130,246,0.1)',
    border: 'rgba(59,130,246,0.25)',
    skills: ['Git & GitHub','Docker', 'Cloudinary', 'Firebase', 'Postman', 'Vercel', 'Render', 'VS Code'],
  },
];

export const SKILL_PROFICIENCY = [
  // Frontend
  { name: 'React.js', level: 90, category: 'Frontend' },
  { name: 'JavaScript', level: 88, category: 'Frontend' },
  { name: 'Tailwind CSS', level: 85, category: 'Frontend' },
  { name: 'HTML5/CSS3', level: 90, category: 'Frontend' },

  // Backend
  { name: 'Node.js', level: 90, category: 'Backend' },
  { name: 'Express.js', level: 85, category: 'Backend' },
  { name: 'FastAPI', level: 80, category: 'Backend' },
  { name: 'RESTful APIs', level: 90, category: 'Backend' },

  // Database
  { name: 'MongoDB', level: 85, category: 'Database' },
  { name: 'PostgreSQL', level: 25, category: 'Database' },

  // AI/ML
  { name: 'RAG Pipelines', level: 60, category: 'AI/ML' },
  { name: 'FAISS', level: 50, category: 'AI/ML' },
  { name: 'Python', level: 70, category: 'AI/ML' },

  // DevOps
  { name: 'Git/GitHub', level: 90, category: 'DevOps' },
  { name: 'Docker', level: 85, category: 'DevOps' },
  { name: 'Vercel', level: 85, category: 'DevOps' },
  { name: 'AWS Basics', level: 65, category: 'DevOps' },
];

export const CORE_PROJECTS = [
  {
    id: 'finchatbot',
    emoji: '🤖',
    title: 'FinChatBot',
    subtitle: 'AI Chatbot for Financial Document Analysis',
    category: 'Full-Stack & AI',
    techStack: [
      { label: 'React 18', color: '#61DAFB' },
      { label: 'Node.js', color: '#68A063' },
      { label: 'Python', color: '#3776AB' },
      { label: 'FastAPI', color: '#009688' },
      { label: 'MongoDB', color: '#47A248' },
      { label: 'LangChain', color: '#1C3C3C' },
    ],
    features: [
      'RAG pipeline built with LangChain and FAISS vector store',
      'Uses both Groq LLM and Google Gemini for better answer quality',
      'WebSocket-based chat so responses show up instantly',
      'Works with PDF, Excel, and CSV files',
      'JWT-based auth keeps uploaded documents secure',
      'Pulls out financial insights from your documents in plain language',
    ],
    githubUrl: 'https://github.com/Sarth00718/Financial-Chatbot-',
    liveUrl: 'http://finchatbot-alb-2082232672.us-east-1.elb.amazonaws.com/',
  },
  {
    id: 'expense-tracker',
    emoji: '💰',
    title: 'Smart Expense Tracker',
    subtitle: 'Personal Finance Tracker with AI Insights',
    category: 'Full-Stack & AI',
    techStack: [
      { label: 'MongoDB', color: '#47A248' },
      { label: 'Express.js', color: '#94a3b8' },
      { label: 'React 18', color: '#61DAFB' },
      { label: 'Node.js', color: '#68A063' },
      { label: 'Tesseract', color: '#4285F4' },
    ],
    features: [
      'Chat with an AI assistant to understand your spending habits',
      'Scan receipts with OCR — no manual entry needed',
      'Spending breakdowns with a simple health score',
      'Budget suggestions based on how you actually spend',
      'Works smoothly on mobile as a PWA',
      'Deployed on Vercel with 99.9% uptime',
    ],
    githubUrl: 'https://github.com/Sarth00718/Smart-Expense-Tracker',
    liveUrl: 'https://smart-expense-tracker-rho-eight.vercel.app/',
  },
  {
    id: 'vastra',
    emoji: '👗',
    title: 'Vastra',
    subtitle: 'A Full MERN Stack Clothing Store',
    category: 'Full-Stack & AI',
    techStack: [
      { label: 'React 18', color: '#61DAFB' },
      { label: 'Node.js', color: '#68A063' },
      { label: 'MongoDB', color: '#47A248' },
      { label: 'Firebase', color: '#FFCA28' },
      { label: 'Razorpay', color: '#3395FF' },
    ],
    features: [
      'Payments handled through Razorpay',
      'Login with email or social accounts via Firebase',
      'Cart and wishlist that actually work the way you expect',
      'Admin panel to manage products and stock',
      'Order tracking so customers know where their stuff is',
      'Deployed on Vercel',
    ],
    githubUrl: 'https://github.com/Sarth00718/Vastra-cloth-shop',
    liveUrl: 'http://vastra-shop-frontend-665651551502.s3-website-us-east-1.amazonaws.com',
  },
  {
    id: 'chat-app',
    emoji: '💬',
    title: 'Real-Time Chat App',
    subtitle: 'MERN Stack Messaging App with WebSockets',
    category: 'Full-Stack & AI',
    techStack: [
      { label: 'Socket.io', color: '#25c2a0' },
      { label: 'Redux Toolkit', color: '#764ABC' },
      { label: 'JWT', color: '#d63aff' },
      { label: 'MongoDB Atlas', color: '#47A248' },
      { label: 'Express.js', color: '#94a3b8' },
    ],
    features: [
      'Messages send and receive in real time with Socket.io',
      'App state managed cleanly with Redux Toolkit',
      'JWT auth so only the right people can access chats',
      'Supports both group chats and private one-on-one conversations',
      'Looks good and works well on mobile too',
      'Hosted on MongoDB Atlas',
    ],
    githubUrl: 'https://github.com/Sarth00718/Real-Time-Chat-Application',
    liveUrl: 'https://real-time-chat-application-eosin.vercel.app',
  },
];

export const HACKATHON_PROJECTS = [
  {
    id: 'smartbite',
    emoji: '🍽️',
    title: 'SmartBite',
    subtitle: 'AI Meal Planner & Nutrition Assistant',
    category: 'Hackathon',
    tagline: 'Mind Sprint 48-Hour International Hackathon (IronXman, Unstop)',
    techStack: [
      { label: 'React', color: '#61DAFB' },
      { label: 'Node.js', color: '#68A063' },
      { label: 'Groq AI', color: '#FF5500' },
      { label: 'K-Means', color: '#8B5CF6' },
      { label: 'PWA', color: '#5A0BF8' },
    ],
    features: [
      'Personalized meal suggestions using collaborative filtering and ML models',
      'Real-time macro tracking with dietary goal monitoring',
      'Weekly meal planning respecting dietary restrictions',
      'AI nutrition chat powered by Groq AI',
      'Meal diversity via K-Means clustering to avoid repetition',
      'Automatic grocery list generator with budget awareness',
      'Responsive dark/light mode UI with PWA offline support',
      'Progress tracking with visual health charts',
    ],
    githubUrl: 'https://github.com/Sarth00718/SmartBite',
  },
  {
    id: 'clipcrafters',
    emoji: '🎬',
    title: 'ClipCrafters',
    subtitle: 'Turn Your Documents into Videos with AI',
    category: 'Hackathon',
    tagline: 'Innovation Award — National Hackathon 2025',
    techStack: [
      { label: 'LangChain', color: '#1C3C3C' },
      { label: 'FAISS', color: '#2176FF' },
      { label: 'Groq LLM', color: '#FF5500' },
      { label: 'MoviePy', color: '#06B6D4' },
      { label: 'Cloudinary', color: '#3448C5' },
    ],
    features: [
      'Upload PDFs, DOCX, PPTX, or TXT files and it parses them automatically',
      'RAG pipeline with FAISS + SentenceTransformers for context retrieval',
      'Groq LLM writes a video script based on your document content',
      'Converts the script into a video using MoviePy with scene transitions',
      'Edit scenes with a simple timeline interface before finalizing',
      'Murf TTS adds a voiceover in multiple voice options',
      'Generates visuals for each scene using Stability.ai',
      'Videos stored and delivered fast via Cloudinary CDN',
    ],
    githubUrl: 'https://github.com/Sarth00718/ClipCrafters',
    liveUrl: null,
  },
  {
    id: 'fleetflow',
    emoji: '🚛',
    title: 'FleetFlow',
    subtitle: 'Fleet & Logistics Management System',
    category: 'Hackathon',
    tagline: 'Built in a 72-hour development sprint',
    techStack: [
      { label: 'PostgreSQL', color: '#336791' },
      { label: 'React', color: '#61DAFB' },
      { label: 'JWT', color: '#d63aff' },
      { label: 'REST API', color: '#10B981' },
    ],
    features: [
      'PostgreSQL database with well-structured queries for fast lookups',
      'Role-based access for drivers, managers, and admins',
      'Live GPS tracking with route suggestions and geofence alerts',
      'Finance dashboard with INR support and tax breakdowns',
      'REST API with JWT auth and rate limiting',
      'Charts for fleet performance and cost trends',
    ],
    githubUrl: 'https://github.com/Sarth00718/FleetFlow',
    liveUrl: 'https://fleet-flow-amber.vercel.app/',
  },
  {
    id: 'exesman',
    emoji: '💼',
    title: 'Exe$Man',
    subtitle: 'Multi-Level Expense Approval & Management System',
    category: 'Hackathon',
    tagline: 'Built to simplify corporate expense workflows',
    techStack: [
      { label: 'React', color: '#61DAFB' },
      { label: 'Node.js', color: '#68A063' },
      { label: 'OCR', color: '#4285F4' },
      { label: 'Express', color: '#94a3b8' },
    ],
    features: [
      'Scan receipts with OCR and skip the manual data entry',
      'Multi-level approval flows configurable per team or department',
      'Real-time notifications when something needs your approval',
      'Reports broken down by department with budget vs. spend tracking',
      'Auto-categorizes expenses and flags anything that breaks policy',
      'Email alerts for approvals and monthly spend summaries',
    ],
    githubUrl: 'https://github.com/Sarth00718/Expense-Management',
    liveUrl: 'https://expense-management-gamma.vercel.app/',
  },
];

export const ML_PROJECTS = [
  {
    id: 'wine-quality',
    emoji: '🍷',
    title: 'Wine Quality Prediction',
    subtitle: 'Comparing 14 ML Algorithms Side by Side',
    category: 'Machine Learning',
    techTags: ['XGBoost', 'LightGBM', 'CatBoost', 'Random Forest', 'SVM'],
    description:
      'Tested 14 different ML algorithms to see which ones classify wine quality best from physicochemical data. Spent time on feature engineering, hyperparameter tuning, and ensemble methods to push the numbers up.',
    githubUrl: 'https://github.com/Sarth00718/Wine-Quality-Prediction',
    highlights: [
      'Feature engineering with correlation analysis',
      'Stratified K-fold cross-validation',
      'Ensemble stacking for a final accuracy boost',
      'Clear performance comparison charts across all models',
    ],
  },
  {
    id: 'heart-attack',
    emoji: '❤️',
    title: 'Heart Attack Risk Prediction',
    subtitle: 'Clinical Risk Classification',
    category: 'Machine Learning',
    techTags: ['KNN Classifier', 'Logistic Regression', 'Decision Trees'],
    description:
      'Built a model to predict heart attack risk from clinical data. Handled class imbalance with SMOTE, scaled features properly, and evaluated results with ROC-AUC curves the way you would expect for a medical use case.',
    githubUrl: 'https://github.com/Sarth00718/heart-attack-prediction',
    highlights: [
      'Clean preprocessing pipeline for medical data',
      'SMOTE to handle imbalanced classes',
      'ROC-AUC evaluation',
      'Feature importance to understand what the model relies on',
    ],
  },
  {
    id: 'superstore',
    emoji: '🌍',
    title: 'Global Superstore Analytics',
    subtitle: 'Analysis of 51K+ Retail Records',
    category: 'Machine Learning',
    techTags: ['Decision Tree', 'Linear Regression', 'K-Means Clustering', 'Tableau'],
    description:
      'Dug into a large global retail dataset to find patterns and build sales forecasts. Created interactive Tableau dashboards so the insights are actually easy to explore — not just numbers in a notebook.',
    githubUrl: 'https://github.com/Sarth00718/Data-Analysis-and-Visualization-of-Global_Superstore-Dataset',
    highlights: [
      'Sales forecasting using time series analysis',
      'Customer segmentation with K-Means',
      'Interactive Tableau dashboards',
      'Profit optimization recommendations',
    ],
  },
];

export const DSA_PROJECTS = [
  {
    id: 'tournament-graph',
    icon: '📊',
    title: 'Tournament Graph Scheduling System',
    techStack: 'Python · FastAPI · NetworkX · React · D3.js · Recharts',
    category: 'DSA & CS Fundamentals',
    description:
      'A tournament scheduler built on graph theory. Uses Welsh-Powell graph coloring to avoid scheduling conflicts and Dijkstra algorithm to minimize travel between venues. D3.js handles the interactive visualizations — conflict graphs, adjacency matrices, and bracket trees.',
    githubUrl: 'https://github.com/Sarth00718/Tournament-Graph-Scheduling-System',
    liveUrl: 'https://tournament-graph-scheduling-system.vercel.app/',
    highlights: [
      'Welsh-Powell coloring for conflict-free scheduling',
      'Dijkstra shortest path for travel optimization',
      'Interactive graph visualizations with D3.js',
      'FastAPI backend with clean REST endpoints',
    ],
  },
  {
    id: 'greedy-visualizer',
    icon: '🎯',
    title: 'Greedy Algorithm Visualizer',
    techStack: 'JavaScript · HTML5 Canvas · CSS3',
    category: 'DSA & CS Fundamentals',
    description:
      'A browser-based tool to watch greedy algorithms run step by step. Covers Activity Selection, Huffman Coding, and Fractional Knapsack — with live complexity info so you can see how each decision affects performance.',
    githubUrl: 'https://github.com/Sarth00718/Greedy-Algorithm-Stimulation',
    liveUrl: 'https://greedy-algorithm-stimulation-hbgc.vercel.app/',
    highlights: [
      'Step-by-step animated execution',
      'Three greedy algorithms implemented',
      'Live time complexity display',
      'Adjustable inputs to test different scenarios',
    ],
  },
  {
    id: 'torrent-billing',
    icon: '⚡',
    title: 'Torrent Power Billing System',
    techStack: 'C++ · OOP · File Handling · STL',
    category: 'DSA & CS Fundamentals',
    description:
      'A console app for managing utility billing. Handles customer accounts, generates bills, processes payments, and calculates late fees — all saved to files so data persists between runs.',
    githubUrl: 'https://github.com/Sarth00718/DSA-LL-Electricity-Billing-System',
    highlights: [
      'OOP design with inheritance and polymorphism',
      'File-based storage so data is not lost on exit',
      'Automated billing and late fee logic',
      'Basic customer account management',
    ],
  },
  {
    id: 'library-management',
    icon: '📚',
    title: 'Library Management System',
    techStack: 'Java · OOP · File I/O · Collections Framework',
    category: 'DSA & CS Fundamentals',
    description:
      'A library system that covers the basics — adding books, registering members, issuing and returning books, tracking fines, and searching the catalog. Built with Java Collections for efficient in-memory operations and file I/O to keep data saved.',
    githubUrl: 'https://github.com/Sarth00718/Library-Management-System---Java',
    highlights: [
      'Full CRUD for books and members',
      'Issue/return tracking with due dates',
      'Automatic fine calculation',
      'Search and filter across the catalog',
    ],
  },
];

export const EXPERIENCE = [
  {
    id: 'unikwork-intern',
    role: 'Full Stack Developer Intern',
    company: 'UNIKWORK',
    type: 'Summer Internship',
    duration: 'May 2026 – June 2026',
    location: 'Surat, Gujarat, India',
    logo: '/unikwork.png',
    color: '#10B981',
    description:
      'Worked as a Full Stack Developer Intern on the UNIKWORK Dashboard, contributing to the development of a production-level project used for project management, task tracking, and business workflow management. Collaborated closely with senior frontend and backend developers in an agile development environment.',
    contributions: [
      'Developed and enhanced production-ready React.js and Next.js components following reusable and scalable architecture',
      'Integrated multiple REST APIs into frontend modules for projects, clients, employees, assets, tasks, and authentication',
      'Built dynamic task management features including board view, list view, task details, and task updates',
      'Implemented advanced filtering, searching, sorting, pagination, and server-side data handling',
      'Fixed responsive design issues across desktop, tablet, and mobile devices with pixel-perfect layouts',
      'Debugged frontend and backend issues, resolved API integration problems, and optimized application performance',
      'Collaborated daily with senior developers through code reviews, feature discussions, and debugging sessions',
    ],
    techStack: [
      { name: 'React.js', color: '#61DAFB' },
      { name: 'Next.js', color: '#000000' },
      { name: 'JavaScript', color: '#F7DF1E' },
      { name: 'TypeScript', color: '#3178C6' },
      { name: 'Tailwind CSS', color: '#06B6D4' },
      { name: 'Node.js', color: '#68A063' },
      { name: 'Express.js', color: '#94a3b8' },
      { name: 'REST APIs', color: '#10B981' },
      { name: 'Git', color: '#F05032' },
      { name: 'Postman', color: '#FF6C37' },
    ],
  },
];

export const TIMELINE = [
  {
    id: '2027',
    year: '2027',
    floor: '09',
    title: 'Graduation',
    subtitle: 'B.Tech Computer Engineering',
    type: 'Milestone',
    description: 'Completing B.Tech from Nirma University with CGPA 9.11. Available for full-time roles from June 2027.',
    color: '#00F5FF',
    items: [
      { icon: '🎓', label: 'B.Tech CGPA', value: '9.11' },
      { icon: '🚀', label: 'Available From', value: 'June 2027' },
    ],
  },
  {
    id: '2026-internship',
    year: '2026',
    floor: '08',
    title: 'Full Stack Developer Intern',
    subtitle: 'UNIKWORK · Surat, Gujarat, India',
    type: 'Internship',
    logoUrl: '/unikwork.png',
    logoAlt: 'Unikwork logo',
    description:
      'Worked as a Full Stack Developer Intern on the UNIKWORK Dashboard — a production-level project for project management, task tracking, and business workflow management. Collaborated closely with senior frontend and backend developers in an agile environment.',
    color: '#10B981',
    items: [
      { icon: '💼', label: 'Role', value: 'Full Stack Intern' },
      { icon: '🏢', label: 'Company', value: 'UNIKWORK' },
      { icon: '📅', label: 'Duration', value: 'May – June 2026' },
      { icon: '📍', label: 'Location', value: 'Surat, Gujarat' },
    ],
  },
  {
    id: '2026-hackamind',
    year: '2026',
    floor: '07',
    title: 'Hackamind Hackathon',
    subtitle: 'Nirma University',
    type: 'Hackathon',
    description:
      'Competed in Hackamind 2026 at Nirma University, focusing on rapid problem-solving, team collaboration, and building a working prototype under pressure.',
    color: '#EC4899',
    items: [
      { icon: '💡', label: 'Event', value: 'Hackamind 2026' },
      { icon: '🏫', label: 'Host', value: 'Nirma University' },
    ],
  },
  {
    id: '2025',
    year: '2025',
    floor: '06',
    title: 'SIH and Mind Sprint',
    subtitle: 'National hackathons and problem-solving challenges',
    type: 'Competitions',
    description:
      'Participated in Smart India Hackathon 2025 and Mind Sprint 48-hour hackathon. Worked on problem statements with a focus on practical problem solving, teamwork, and fast execution.',
    color: '#F59E0B',
    items: [
      { icon: '🇮🇳', label: 'SIH 2025', value: 'Participated' },
      { icon: '⚡', label: 'Mind Sprint', value: '48-Hour Build' },
    ],
  },
  {
    id: '2024-hackathons',
    year: '2024',
    floor: '05',
    title: 'Problem Solving Practice',
    subtitle: 'Codeforces and LeetCode',
    type: 'Competitive Programming',
    description:
      'Focused on competitive programming in 2024 through Codeforces and LeetCode. Built consistency in algorithms, data structures, and timed problem solving.',
    color: '#3B82F6',
    items: [
      { icon: '🏆', label: 'Codeforces', value: 'Contest Practice' },
      { icon: '🧩', label: 'LeetCode', value: 'Problem Solving' },
    ],
  },
  {
    id: '2023',
    year: '2023',
    floor: '03',
    title: 'Started B.Tech',
    subtitle: 'Nirma University',
    type: 'Education',
    description:
      'Began B.Tech in Computer Engineering at Nirma University. Built foundations in data structures, algorithms, OOP, databases, and full-stack development.',
    color: '#4F8CFF',
    items: [
      { icon: '🏫', label: 'University', value: 'Nirma University' },
      { icon: '📜', label: 'Roll No', value: '23BCE194' },
    ],
  },
];

export const ACHIEVEMENTS = [
  {
    id: 'amazon-ml-2025',
    title: 'Amazon ML Summer School 2025',
    organization: 'Amazon',
    date: 'July 2025',
    type: 'Selection',
    description:
      'Selected from a national pool of top engineering students for Amazon prestigious Machine Learning Summer School program.',
    icon: '🏅',
    color: '#F59E0B',
  },
  {
    id: 'sih-2025',
    title: 'Smart India Hackathon 2025',
    organization: 'Government of India',
    date: '2025',
    type: 'Participation',
    description:
      'Participated in India largest open innovation platform, presenting AI-driven solutions to national-level problem statements.',
    icon: '🇮🇳',
    color: '#10B981',
  },
  {
    id: 'hackamind-nirma',
    title: 'Hackamind Hackathon',
    organization: 'Nirma University',
    date: '2024',
    type: 'Participation',
    description:
      'Participated in university-level hackathon focused on innovative problem-solving and rapid prototyping.',
    icon: '💡',
    color: '#EC4899',
  },
  {
    id: 'mind-sprint-2024',
    title: 'Mind Sprint Hackathon — IronXman',
    organization: 'Unstop',
    date: '2024',
    type: 'Participation',
    description:
      'Competed in 48-hour national-level hackathon, building full-stack AI-integrated solutions under time constraints.',
    icon: '⚡',
    color: '#3B82F6',
  },
];

export const CP_PROFILES = [
  {
    platform: 'LeetCode',
    handle: '__sarth_narola_007',
    link: 'https://leetcode.com/u/__sarth_narola_007/',
    status: 'Active Problem Solver',
    description:
      'Consistently solving problems across all difficulty levels with focus on algorithms and data structures',
    color: '#F59E0B',
  },
  {
    platform: 'Codeforces',
    handle: 'sarthnarola007',
    link: 'https://codeforces.com/profile/sarthnarola007',
    status: 'Competitive Programmer',
    description:
      'Participating in contests to improve problem-solving skills and algorithmic thinking',
    color: '#3B82F6',
  },
  {
    platform: 'CodeChef',
    handle: 'mds_007',
    link: 'https://www.codechef.com/users/mds_007',
    status: '2★ Coder',
    description:
      'Actively participating in monthly challenges and improving competitive programming skills',
    color: '#A16207',
  },
];

export const CERTIFICATES = [
  {
    id: 'amazon-ml-2025',
    title: 'Amazon ML Summer School 2025',
    issuer: 'Amazon',
    category: 'Machine Learning',
    date: 'July 2025',
    description:
      'Selected for Amazon ML Summer School 2025. Covered supervised learning, deep learning, NLP, probabilistic graphical models, sequential models, and recommendation systems — taught by Amazon Scientists.',
    skills: ['Machine Learning', 'Deep Learning', 'NLP', 'Recommendation Systems'],
    color: '#F59E0B',
    icon: '🏅',
    featured: true,
  },
  {
    id: 'hackamind-nirma',
    title: 'Hackamind Hackathon',
    issuer: 'Nirma University',
    category: 'Hackathon',
    date: '2024',
    description:
      'Took part in Nirma University Hackamind hackathon — built a working prototype under time pressure, collaborated with the team, and tackled a real problem from scratch.',
    skills: ['Rapid Prototyping', 'Team Collaboration', 'Problem-Solving'],
    color: '#EC4899',
    icon: '💡',
    featured: true,
  },
  {
    id: 'mind-sprint-2024',
    title: 'Mind Sprint Hackathon — IronXman',
    issuer: 'Unstop',
    category: 'Hackathon',
    date: '2024',
    certificateUrl: '/MIND.pdf',
    description:
      'Competed in the Mind Sprint 48-hour hackathon (IronXman track) on Unstop. Built and shipped a full-stack AI project with the team within the deadline.',
    skills: ['Full Stack', 'AI/ML', 'Rapid Prototyping'],
    color: '#3B82F6',
    icon: '⚡',
    featured: true,
  },
  {
    id: 'sih-2025',
    title: 'Smart India Hackathon 2025',
    issuer: 'Government of India',
    category: 'National Hackathon',
    date: '2025',
    certificateUrl: '/SIH2025.pdf',
    description:
      'Participated in Smart India Hackathon 2025 — India largest open innovation event run by the Government of India. Our team built an AI-based solution for a national problem statement and competed against teams from across the country.',
    skills: ['AI Solutions', 'Team Leadership', 'System Design'],
    color: '#10B981',
    icon: '🇮🇳',
    featured: true,
  },
];

export const NAV_SECTIONS = [
  { id: 'hero', label: 'Arrival', icon: '🚀' },
  { id: 'about', label: 'About', icon: '🪐' },
  { id: 'skills', label: 'Skills', icon: '⚛️' },
  { id: 'experience', label: 'Experience', icon: '💼' },
  { id: 'projects', label: 'Projects', icon: '🌌' },
  { id: 'timeline', label: 'Timeline', icon: '🛗' },
  { id: 'achievements', label: 'Trophies', icon: '🏆' },
  { id: 'certificates', label: 'Museum', icon: '🏛️' },
  { id: 'contact', label: 'Contact', icon: '🌀' },
];
